// <auto-generated />
namespace MusicStore.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NewMig8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMig8));
        
        string IMigrationMetadata.Id
        {
            get { return "202505221923551_NewMig8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
